language: java

jdk:
  - oraclejdk8

env:
  global:
  - GH_REF: github.com/hiddenid01/gitTest001
  - secure: "N6VGKAZDZN1NXqlSvLNAHVbJrGwZkSCdYF0D/6au5gcltydBbK3Zqo9n0iTHu0ahg3ZQQDmetys/r3ZLep/VxTB7+Y7AXK4a5VZ2hEumsewSo7tTyKt98p2At/KTpn3x4ndK7uTZAlbG9KJLcACvb27SJajxkVppArDK/o+oeujHcPgIMOK5WezavZ+zG2ngL8idelgXLV9uP3rDHSjaO1ImhkxdEzjF6r4uj2FoQCCpMzuuA4GPna9F3P7bmglIZmoskhaJPs7kcNhS6UBDqpLsiBz9D2moNGvfutM3BWfHYSPWuwpyxe4+kgMXovHKMp2a3+wUxZ7UK7OgRjqp35QR3fsCmhFV36aPBDjLUCx5cAVNzzkjkIQpTja5BWdWxFbURcS5vAB1vnvwy/QBxaKluMj/HZ4wYTCLZrV59MWNy5v2165h/Q/i6Dtcb0QF2z1WzIpxn2ScdZsMTO6SafRhEWBqT4gCv1i4TTqBfh06DqjxWHjM/EpjNQrjIMuCRtPCe7RsStQixSgmbxyLg6tNYt5jM9k0JB8W7qr6niR/1fxjq3NfrgukRJb+pKWzHzh4ir5B923Rz80l73e9BNTcPEy09yx3u/LGUi0clS9TaN3ZmWR8u7Y19kGDSCIuMiZ3do3hyTwg9ThnqQn5Es0fgavn0cJfoJZphyLUgUM="

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  
after_success:
  - mvn clean test jacoco:report coveralls:report
  - bash update-ghpages.sh

# Migration to container-based infrastructure  
sudo: false

addons:
  artifacts:
    debug: true
    paths:
    - $(git ls-files -o | tr "\n" ":")
    - $(ls /var/log/*.log | tr "\n" ":")
    - $HOME/some/other/thing.log
    target_paths: $TRAVIS_BUILD_NUMBER
    working_dir: WORKING_DIR
    bucket: uss001
    s3_region: us-east-1
    
#  coverity_scan:
#    project:
#      name: "hiddenid01/gitTest001"
#      description: "Build submitted via Travis CI"
#    notification_email: hiddenid@naver.com
#    build_command_prepend: "mvn clean"
#    build_command:   "mvn -DskipTests=true compile"
#    branch_pattern: coverity_scan
