language: java

jdk:
  - oraclejdk8

env:
  global:
  - GH_REF: github.com/hiddenid01/gitTest001
  - secure: "CY4P7lxfoyjAbULoetIc8cunqnv4a7GPkhBVAT/dexcQurz0Eq/22dKLLbELYMyxn7WdCBOvOsVADsjxbAk06fFmWCeB7jUzITzb3aE4KGAVbkJxgcj9JIPfLmcn/PCsB9eKcwfaXGWTRCUoBOH7ulB75MUt7xwZji6F71EzXIFImTTePyw8hy9arIelFhrUeCSkPud42EILJdzCdAi3USpld8naEPzJGZL+uyNNHcw6RQo8vAxejka44JKJrpK1WIoCC8Uji446nQQgD/y0boFYBRnx8v2phecq2gSKJ4UxQ9OQHvSRVPq5AkcOuZu6Wr3wLpncDfTwSbEkQudLPaNlP8d2iSpkMvVJ3aLKlJWsjfr00+9MB+zk3EdXeJflWmo/YeegTtBJ0KwSvxx2c8HywlLOCX9cteMv2PPFTZEygTPdP0TSJ5opSnHEUEzB/VhsjwcoWKGoOQDEamKV+XeOMb2nKdgb15v+piSz6Mvfsrp0XMo2QnrnBxyudjheXdn2+lhCdjzb9fa38IV50qxjBPb3jFURtZ4GKuEX4wiy688tFoI/lxvwz8sYgsb8OxtcnvrLECOZsOKfEcrq0I3W1zng/YadoVKBrHALGyiAgM9ogVxp3mEcLRfi3aqHPJq9PFD8Eg+L7pIBE8Nd1k34xnx/J9b7+aOiNzYVuJA="

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  
after_success:
  - mvn clean test jacoco:report coveralls:report
  - bash update-ghpages.sh

# Migration to container-based infrastructure  
sudo: false

addons:
  artifacts: true
	debug: true
  s3_region: "us-east-1"
  coverity_scan:
    project:
      name: "hiddenid01/gitTest001"
      description: "<Your project description here>"
    notification_email: hiddenid@naver.com
    build_command_prepend: "<Your build preprocessing command here>"
    build_command:   "<Your build command here>"
    branch_pattern: coverity_scan
